---
apiVersion: v1
kind: Namespace
metadata:
  name: tenantthreenamespace
  labels:
    role: tenantthreenamespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-tenantthree-quota
  namespace: tenantthreenamespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi