kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs-tenantthreenamespace
  namespace: tenantthreenamespace
provisioner: test.com/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-tenantthreenamespace
  namespace: tenantthreenamespace
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi