apiVersion: v1
kind: Namespace
metadata:
  name: tenantonenamespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: tenantonenamespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
